os:
  - "linux"
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "10"
before_install:
  - wget https://chromedriver.storage.googleapis.com/75.0.3770.140/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - ln -s $(pwd)/chromedriver ~/bin/chromedriver
install:
  - npm i
  - npm run start-server
script:
  - npm run api-test
  - npm run browser-test
