dist: xenial
addons:
  chrome: stable
language: node_js
node_js:
  - "10"
before_install:
  - CHROME_VERSION=$(google-chrome --product-version)
  - echo ${CHROME_VERSION}
  - wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - ln -s $(pwd)/chromedriver ~/bin/chromedriver
install:
  - npm i
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - npm run start-server >/dev/null 2>&1
script:
  - npm run api-test
  - npm run browser-test
