os:
  - "linux"
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "10"
before_install:
  - wget https://chromedriver.storage.googleapis.com/75.0.3770.140/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - ln -s ./chromedriver ~/bin/chromedriver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm run start-server
  - npm i
script:
  - npm run api-test
  - npm run browser-test
